update work flow  BLUE-GREEN Deployment

diff --git a/.github/workflows/deploy-docs.yml b/.github/workflows/deploy-docs.yml
--- a/.github/workflows/deploy-docs.yml
+++ b/.github/workflows/deploy-docs.yml
@@ -1,5 +1,5 @@
 
-name: Deploy Docs
+name: Deploy Docs with BLUE-GREEN Deployment
 
 on:
   push:
@@ -7,6 +7,7 @@ on:
       - 'docs/.vuepress/public/repos_data.json'
     branches:
       - main
+  workflow_dispatch:
 
 permissions:
   contents: write
@@ -21,8 +22,6 @@ jobs:
           fetch-depth: 0
           # if your docs needs submodules, uncomment the following line
           # submodules: true
-
-
 
       - name: Setup Node.js
         uses: actions/setup-node@v3
@@ -40,9 +39,30 @@ jobs:
           npm run docs:build
           > docs/.vuepress/dist/.nojekyll
 
+      # Staging Deployment
+      - name: Move Build to Staging
+        run: mv docs/.vuepress/dist staging
+
+      # Validate the build
+      - name: Validate Staging
+        run: |
+          if [ -d "staging" ]; then
+            echo "Staging build successful"
+          else
+            echo "Staging build failed"
+            exit 1
+          fi
+
+      # Production Deployment
+      - name: Move Build to Production
+        run: |
+          mv prodictoin backup || true
+          mv staging production
+
+      # Deploy to GitHub Pages
       - name: Deploy Docs
         uses: JamesIves/github-pages-deploy-action@v4
         with:
           # This is the branch where the docs are deployed to
           branch: gh-pages
-          folder: docs/.vuepress/dist
+          folder: production
